## Aqui fazemos a primeira etapa do code, onde é feito o processamento dos dados baixados da ação correspondente, direto do site da Fundamentus. São explicados todos os passos do processamento.

In [1]:
import numpy as np
import pandas as pd
import pandas_datareader.data as web
from datetime import datetime
import yfinance as yf

pd.set_option('display.width', 1000)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

# DADOS FUNDAMENTALISTAS - FUNDAMENTUS

Ao fazer o download do site da Fundamentus, os dados vem em formato excel, então pegamos e convertemos facilmente para cvs.

Aqui trazemos o csv da ação para o notebook. Ele necessita do ".T" para que ele faça uma transposição, pois os atributos estavam nas linhas e as amostras nas colunas, assim invertemos isso, ficando no formato convencional utilizado.

Após, dropamos uma coluna inútil.

A coluna que mostra as datas, que estão separadas por trimestre, fica com um título NaN e está na primeira posição das colunas, assim precisamos atribuir o devido nome a coluna.

Assim, criamos uma coluna chamada "Data Trimeste", ao que lhe é atribuida as datas, e na sequência deletamos a coluna com o títlo NaN, através do iloc que engloba apenas colunas que tenham título "notnull"(naõ nulos).


A coluna "Data Trimestre" fica posicionada como última coluna do dataset, para ficar mais claro, apagamos, colocamos em uma variavel auxiliar, e a inserimos na primeira posição das colunas.

In [2]:
# COMEÇA O CÓDIGO QUE EXTRAI OS DADOS FUNDAMENTALISTAS

fundamental_data = pd.read_csv("mult3.csv",index_col=0, header=None).T
fundamental_data.drop(columns = 'XLSWrite 1.34 Copyright(c) 1999,2000 Axolot Data', inplace = True)


fundamental_data['Data Trimestre'] = fundamental_data.iloc[0:,0]
fundamental_data = fundamental_data.iloc[:, fundamental_data.columns.notnull()]

data = fundamental_data['Data Trimestre']
fundamental_data.drop(labels=['Data Trimestre'], axis=1,inplace = True)
fundamental_data.insert(0, 'Data Trimestre', data)

fundamental_data.head()

,Data Trimestre,Ativo Total,Ativo Circulante,Caixa e Equivalentes de Caixa AC,Aplicações Financeiras AC,Contas a Receber AC,Estoques AC,Ativos Biológicos AC,Tributos a Recuperar AC,Despesas Antecipadas AC,Outros Ativos Circulantes AC,Ativo Realizavel Longo Prazo,Aplicações Financeiras Avaliadas a Valor Justo ACLP,Aplicações Financeiras Avaliadas ao Custo Amortizado ACLP,Contas a Receber ACLP,Estoques ACLP,Ativos Biológicos ACLP,Tributos Diferidos ACLP,Despesas Antecipadas ACLP,Créditos com Partes Relacionadas ACLP,Outros Ativos Não Circulantes ACLP,Investimentos,Imobilizado,Intangível,Diferido,Passivo Total,Passivo Circulante,Obrigações Sociais e Trabalhistas PC,Fornecedores PC,Obrigações Fiscais PC,Empréstimos e Financiamentos PC,Passivos com Partes Relacionadas PC,Dividendos e JCP a Pagar PC,Outros PC,Provisões PC,Passivos sobre Ativos Não-Correntes a Venda e Descontinuados PC,Passivo Não Circulante,Empréstimos e Financiamentos PNC,Passivos com Partes Relacionadas PNC,Outros PNC,Tributos Diferidos PNC,Adiantamento para Futuro Aumento Capital PNC,Provisões PNC,Passivos sobre Ativos Não-Correntes a Venda e Descontinuados PNC,Lucros e Receitas a Apropriar PNC,Participação dos Acionistas Não Controladores,Patrimônio Líquido,Capital Social Realizado,Reservas de Capital,Reservas de Reavaliação,Reservas de Lucros,Lucros/Prejuízos Acumulados,Ajustes de Avaliação Patrimonial,Ajustes Acumulados de Conversão,Outros Resultados Abrangentes,Adiantamento para Futuro Aumento Capital
1,30/06/2019,9.353.538,1.327.623,31.233,881.860,258.808,36.531,0,32.804,0,86.387,666.581,0,0,0,67.482,412.512,0,22.217,0,0,6.913.959,88.930,356.445,0,9.353.538,683.949,0,102.141,24.080,401.613,0,95.811,60.304,0,0,3.181.147,2.719.816,0,247.185,214.146,0,0,0,0,15.542,5.472.900,2.944.514,817.527,0,1.613.708,97.151,0,0,0,0
2,31/03/2019,9.023.956,1.370.233,44.148,961.123,234.324,36.693,0,7.991,0,85.954,668.555,0,0,69.205,410.709,0,21.400,0,0,167.241,6.542.900,88.035,354.233,0,9.023.956,737.606,0,128.480,27.471,422.969,0,129.551,29.135,0,0,2.835.767,2.394.097,0,229.522,212.148,0,0,0,0,16.132,5.434.451,2.944.514,784.265,0,1.613.708,91.964,0,0,0,0
3,31/12/2018,8.875.258,1.274.156,38.864,816.905,284.310,36.415,0,23.081,0,74.581,664.262,0,0,0,68.744,406.768,0,21.613,0,0,6.500.617,80.584,355.639,0,8.875.258,713.933,0,120.345,28.944,396.588,0,129.551,38.505,0,0,2.809.138,2.417.144,0,183.355,208.639,0,0,0,0,16.207,5.335.980,2.944.514,777.758,0,1.613.708,0,0,0,0,0
4,30/09/2018,8.819.852,1.243.000,49.485,792.971,257.599,35.930,0,41.633,0,65.382,665.345,0,0,0,75.054,404.232,0,25.702,0,0,6.474.454,80.911,356.142,0,8.819.852,446.670,0,103.408,36.635,181.321,0,68.959,56.347,0,0,3.066.500,2.702.204,0,153.027,211.269,0,0,0,0,16.782,5.289.900,2.944.514,774.248,0,1.400.232,170.906,0,0,0,0
5,30/06/2018,8.825.800,1.375.582,53.898,920.261,241.316,36.382,0,57.649,0,66.076,534.906,0,0,0,73.362,287.326,0,25.718,0,11.852,6.475.161,83.733,356.418,0,8.825.800,518.942,0,83.698,40.355,231.672,0,94.814,68.403,0,0,3.010.466,2.750.432,0,54.083,205.951,0,0,0,0,17.078,5.279.314,2.944.514,800.244,0,1.400.232,134.324,0,0,0,0

Aqui é o processo de manipulação das datas, muito importante na execução do code.

Primeiro utilizamos pd.to_datetime, função própria do Pandas para que ele entenda o formato e de que se trata de informações sobre data.

Subdividimos em colunas distintas, informações sobre "Dia", "Mês" e "Ano", logo a coluna "Data Trimestre" já não nos era mais útil.

Assim, novamente colocamos as três novas colunas em váriaveis auxiliares, para posiciona-las nas primeiras colunas do dataset.

In [3]:
fundamental_data['Data Trimestre'] = pd.to_datetime(fundamental_data['Data Trimestre'].str.strip(), format='%d/%m/%Y')


fundamental_data["Day"] = fundamental_data['Data Trimestre'].map(lambda x: x.day)
fundamental_data["Month"] = fundamental_data['Data Trimestre'].map(lambda x: x.month)
fundamental_data["Year"] = fundamental_data['Data Trimestre'].map(lambda x: x.year)

fundamental_data.drop(columns = 'Data Trimestre', inplace = True)

year = fundamental_data['Year']
fundamental_data.drop(labels=['Year'], axis=1,inplace = True)
fundamental_data.insert(0, 'Year', year)

month = fundamental_data['Month']
fundamental_data.drop(labels=['Month'], axis=1,inplace = True)
fundamental_data.insert(1, 'Month', month)

day = fundamental_data['Day']
fundamental_data.drop(labels=['Day'], axis=1,inplace = True)
fundamental_data.insert(2, 'Day', day)

fundamental_data.head()

,Year,Month,Day,Ativo Total,Ativo Circulante,Caixa e Equivalentes de Caixa AC,Aplicações Financeiras AC,Contas a Receber AC,Estoques AC,Ativos Biológicos AC,Tributos a Recuperar AC,Despesas Antecipadas AC,Outros Ativos Circulantes AC,Ativo Realizavel Longo Prazo,Aplicações Financeiras Avaliadas a Valor Justo ACLP,Aplicações Financeiras Avaliadas ao Custo Amortizado ACLP,Contas a Receber ACLP,Estoques ACLP,Ativos Biológicos ACLP,Tributos Diferidos ACLP,Despesas Antecipadas ACLP,Créditos com Partes Relacionadas ACLP,Outros Ativos Não Circulantes ACLP,Investimentos,Imobilizado,Intangível,Diferido,Passivo Total,Passivo Circulante,Obrigações Sociais e Trabalhistas PC,Fornecedores PC,Obrigações Fiscais PC,Empréstimos e Financiamentos PC,Passivos com Partes Relacionadas PC,Dividendos e JCP a Pagar PC,Outros PC,Provisões PC,Passivos sobre Ativos Não-Correntes a Venda e Descontinuados PC,Passivo Não Circulante,Empréstimos e Financiamentos PNC,Passivos com Partes Relacionadas PNC,Outros PNC,Tributos Diferidos PNC,Adiantamento para Futuro Aumento Capital PNC,Provisões PNC,Passivos sobre Ativos Não-Correntes a Venda e Descontinuados PNC,Lucros e Receitas a Apropriar PNC,Participação dos Acionistas Não Controladores,Patrimônio Líquido,Capital Social Realizado,Reservas de Capital,Reservas de Reavaliação,Reservas de Lucros,Lucros/Prejuízos Acumulados,Ajustes de Avaliação Patrimonial,Ajustes Acumulados de Conversão,Outros Resultados Abrangentes,Adiantamento para Futuro Aumento Capital
1,2019,6,30,9.353.538,1.327.623,31.233,881.860,258.808,36.531,0,32.804,0,86.387,666.581,0,0,0,67.482,412.512,0,22.217,0,0,6.913.959,88.930,356.445,0,9.353.538,683.949,0,102.141,24.080,401.613,0,95.811,60.304,0,0,3.181.147,2.719.816,0,247.185,214.146,0,0,0,0,15.542,5.472.900,2.944.514,817.527,0,1.613.708,97.151,0,0,0,0
2,2019,3,31,9.023.956,1.370.233,44.148,961.123,234.324,36.693,0,7.991,0,85.954,668.555,0,0,69.205,410.709,0,21.400,0,0,167.241,6.542.900,88.035,354.233,0,9.023.956,737.606,0,128.480,27.471,422.969,0,129.551,29.135,0,0,2.835.767,2.394.097,0,229.522,212.148,0,0,0,0,16.132,5.434.451,2.944.514,784.265,0,1.613.708,91.964,0,0,0,0
3,2018,12,31,8.875.258,1.274.156,38.864,816.905,284.310,36.415,0,23.081,0,74.581,664.262,0,0,0,68.744,406.768,0,21.613,0,0,6.500.617,80.584,355.639,0,8.875.258,713.933,0,120.345,28.944,396.588,0,129.551,38.505,0,0,2.809.138,2.417.144,0,183.355,208.639,0,0,0,0,16.207,5.335.980,2.944.514,777.758,0,1.613.708,0,0,0,0,0
4,2018,9,30,8.819.852,1.243.000,49.485,792.971,257.599,35.930,0,41.633,0,65.382,665.345,0,0,0,75.054,404.232,0,25.702,0,0,6.474.454,80.911,356.142,0,8.819.852,446.670,0,103.408,36.635,181.321,0,68.959,56.347,0,0,3.066.500,2.702.204,0,153.027,211.269,0,0,0,0,16.782,5.289.900,2.944.514,774.248,0,1.400.232,170.906,0,0,0,0
5,2018,6,30,8.825.800,1.375.582,53.898,920.261,241.316,36.382,0,57.649,0,66.076,534.906,0,0,0,73.362,287.326,0,25.718,0,11.852,6.475.161,83.733,356.418,0,8.825.800,518.942,0,83.698,40.355,231.672,0,94.814,68.403,0,0,3.010.466,2.750.432,0,54.083,205.951,0,0,0,0,17.078,5.279.314,2.944.514,800.244,0,1.400.232,134.324,0,0,0,0

Essa é uma parte bem crítica, resetamos o índice(para que ele fique com a contagem correta de 0 até o total de linhas). E você deve estar se perguntando: por quê pegar o dataset a partir da 4 posição ?

Esse dataset está em formato descrescente com base nas datas, então, la no final do projeto, quando formos comparar os algortimos de classificação com a série temporal, para validação temos que comparar com dados que já ocorreram, par ter uma noção do desempenho.

Lembrando que se pegassemos de 0:, nesse caso, ele ia predizer dados a partir do 3T de 2018 até o 3T de 2019, sendo que o TCC estava sendo feito nessa época, então não tinhamos os dados reais necessarios para comparação, então por fins logisticos, reduzimos a ánalise um ano antes, para ao final do trabalho, quando compararmos os fundamentus e os algortimos de classificação com as séries temporais e a LSTM tenhamos tranquilidade para comparar com dados que ocorreram de fato para se ter uma boa base para inferir desempenho e tirar conclusões.

In [4]:
fundamental_data.reset_index(drop=True, inplace=True)
fundamental_data = fundamental_data[4:28]
fundamental_data.reset_index(drop=True, inplace=True)

fundamental_data.head()

,Year,Month,Day,Ativo Total,Ativo Circulante,Caixa e Equivalentes de Caixa AC,Aplicações Financeiras AC,Contas a Receber AC,Estoques AC,Ativos Biológicos AC,Tributos a Recuperar AC,Despesas Antecipadas AC,Outros Ativos Circulantes AC,Ativo Realizavel Longo Prazo,Aplicações Financeiras Avaliadas a Valor Justo ACLP,Aplicações Financeiras Avaliadas ao Custo Amortizado ACLP,Contas a Receber ACLP,Estoques ACLP,Ativos Biológicos ACLP,Tributos Diferidos ACLP,Despesas Antecipadas ACLP,Créditos com Partes Relacionadas ACLP,Outros Ativos Não Circulantes ACLP,Investimentos,Imobilizado,Intangível,Diferido,Passivo Total,Passivo Circulante,Obrigações Sociais e Trabalhistas PC,Fornecedores PC,Obrigações Fiscais PC,Empréstimos e Financiamentos PC,Passivos com Partes Relacionadas PC,Dividendos e JCP a Pagar PC,Outros PC,Provisões PC,Passivos sobre Ativos Não-Correntes a Venda e Descontinuados PC,Passivo Não Circulante,Empréstimos e Financiamentos PNC,Passivos com Partes Relacionadas PNC,Outros PNC,Tributos Diferidos PNC,Adiantamento para Futuro Aumento Capital PNC,Provisões PNC,Passivos sobre Ativos Não-Correntes a Venda e Descontinuados PNC,Lucros e Receitas a Apropriar PNC,Participação dos Acionistas Não Controladores,Patrimônio Líquido,Capital Social Realizado,Reservas de Capital,Reservas de Reavaliação,Reservas de Lucros,Lucros/Prejuízos Acumulados,Ajustes de Avaliação Patrimonial,Ajustes Acumulados de Conversão,Outros Resultados Abrangentes,Adiantamento para Futuro Aumento Capital
0,2018,6,30,8.825.800,1.375.582,53.898,920.261,241.316,36.382,0,57.649,0,66.076,534.906,0,0,0,73.362,287.326,0,25.718,0,11.852,6.475.161,83.733,356.418,0,8.825.800,518.942,0,83.698,40.355,231.672,0,94.814,68.403,0,0,3.010.466,2.750.432,0,54.083,205.951,0,0,0,0,17.078,5.279.314,2.944.514,800.244,0,1.400.232,134.324,0,0,0,0
1,2018,3,31,8.536.529,1.109.223,60.812,705.529,225.510,38.002,0,16.422,0,62.948,532.018,0,0,78.309,277.833,0,25.445,0,0,150.431,6.454.152,86.117,355.019,0,8.536.529,514.126,0,99.432,34.181,266.519,0,40.348,73.646,0,0,2.731.562,2.460.283,0,84.026,187.253,0,0,0,0,16.913,5.273.928,2.944.514,831.033,0,1.400.232,98.149,0,0,0,0
2,2017,12,31,8.644.402,1.299.500,39.786,856.245,277.047,35.959,0,27.281,0,63.182,519.416,0,0,79.164,272.880,0,17.782,0,0,149.590,6.444.021,27.573,353.892,0,8.644.402,699.364,0,102.199,38.011,265.777,0,206.262,87.115,0,0,2.744.725,2.467.936,0,95.245,181.544,0,0,0,0,15.224,5.185.089,2.944.514,840.341,0,1.400.234,0,0,0,0,0
3,2017,9,30,8.724.975,1.442.779,145.357,925.503,245.011,37.474,0,33.336,0,56.098,510.242,0,0,86.213,266.674,0,13.445,0,0,143.910,6.390.804,28.048,353.102,0,8.724.975,679.949,0,118.891,34.536,283.290,0,150.351,92.881,0,0,2.906.118,2.602.877,0,127.485,175.756,0,0,0,0,10.383,5.128.525,2.944.514,854.578,0,1.270.179,59.254,0,0,0,0
4,2017,6,30,8.604.258,1.402.067,114.101,891.072,246.743,49.551,0,41.429,0,59.171,494.026,0,0,96.764,263.469,0,13.309,0,0,120.484,6.329.868,28.565,349.732,0,8.604.258,693.976,0,81.047,40.527,378.119,0,94.488,99.795,0,0,2.789.616,2.474.044,0,138.700,176.872,0,0,0,0,8.360,5.112.306,2.944.514,848.735,0,1.270.179,48.878,0,0,0,0

Para fins didáticos, criei uma coluna "Quarter" que indica qual trimestre corresponde aquela linha, e a posicionei na primeira posição das colunas.

In [5]:
fundamental_data['Quarter'] = '2Q2018', '1Q2018', '4Q2017', '3Q2017', '2Q2017', '1Q2017', '4Q2016', '3Q2016', '2Q2016', '1Q2016', '4Q2015', '3Q2015', '2Q2015', '1Q2015','4Q2014', '3Q2014', '2Q2014', '1Q2014','4Q2013', '3Q2013', '2Q2013', '1Q2013', '4Q2012', '3Q2012'

quarter = fundamental_data['Quarter']
fundamental_data.drop(labels=['Quarter'], axis=1, inplace=True)
fundamental_data.insert(0, 'Quarter', quarter)

fundamental_data.head()

,Quarter,Year,Month,Day,Ativo Total,Ativo Circulante,Caixa e Equivalentes de Caixa AC,Aplicações Financeiras AC,Contas a Receber AC,Estoques AC,Ativos Biológicos AC,Tributos a Recuperar AC,Despesas Antecipadas AC,Outros Ativos Circulantes AC,Ativo Realizavel Longo Prazo,Aplicações Financeiras Avaliadas a Valor Justo ACLP,Aplicações Financeiras Avaliadas ao Custo Amortizado ACLP,Contas a Receber ACLP,Estoques ACLP,Ativos Biológicos ACLP,Tributos Diferidos ACLP,Despesas Antecipadas ACLP,Créditos com Partes Relacionadas ACLP,Outros Ativos Não Circulantes ACLP,Investimentos,Imobilizado,Intangível,Diferido,Passivo Total,Passivo Circulante,Obrigações Sociais e Trabalhistas PC,Fornecedores PC,Obrigações Fiscais PC,Empréstimos e Financiamentos PC,Passivos com Partes Relacionadas PC,Dividendos e JCP a Pagar PC,Outros PC,Provisões PC,Passivos sobre Ativos Não-Correntes a Venda e Descontinuados PC,Passivo Não Circulante,Empréstimos e Financiamentos PNC,Passivos com Partes Relacionadas PNC,Outros PNC,Tributos Diferidos PNC,Adiantamento para Futuro Aumento Capital PNC,Provisões PNC,Passivos sobre Ativos Não-Correntes a Venda e Descontinuados PNC,Lucros e Receitas a Apropriar PNC,Participação dos Acionistas Não Controladores,Patrimônio Líquido,Capital Social Realizado,Reservas de Capital,Reservas de Reavaliação,Reservas de Lucros,Lucros/Prejuízos Acumulados,Ajustes de Avaliação Patrimonial,Ajustes Acumulados de Conversão,Outros Resultados Abrangentes,Adiantamento para Futuro Aumento Capital
0,2Q2018,2018,6,30,8.825.800,1.375.582,53.898,920.261,241.316,36.382,0,57.649,0,66.076,534.906,0,0,0,73.362,287.326,0,25.718,0,11.852,6.475.161,83.733,356.418,0,8.825.800,518.942,0,83.698,40.355,231.672,0,94.814,68.403,0,0,3.010.466,2.750.432,0,54.083,205.951,0,0,0,0,17.078,5.279.314,2.944.514,800.244,0,1.400.232,134.324,0,0,0,0
1,1Q2018,2018,3,31,8.536.529,1.109.223,60.812,705.529,225.510,38.002,0,16.422,0,62.948,532.018,0,0,78.309,277.833,0,25.445,0,0,150.431,6.454.152,86.117,355.019,0,8.536.529,514.126,0,99.432,34.181,266.519,0,40.348,73.646,0,0,2.731.562,2.460.283,0,84.026,187.253,0,0,0,0,16.913,5.273.928,2.944.514,831.033,0,1.400.232,98.149,0,0,0,0
2,4Q2017,2017,12,31,8.644.402,1.299.500,39.786,856.245,277.047,35.959,0,27.281,0,63.182,519.416,0,0,79.164,272.880,0,17.782,0,0,149.590,6.444.021,27.573,353.892,0,8.644.402,699.364,0,102.199,38.011,265.777,0,206.262,87.115,0,0,2.744.725,2.467.936,0,95.245,181.544,0,0,0,0,15.224,5.185.089,2.944.514,840.341,0,1.400.234,0,0,0,0,0
3,3Q2017,2017,9,30,8.724.975,1.442.779,145.357,925.503,245.011,37.474,0,33.336,0,56.098,510.242,0,0,86.213,266.674,0,13.445,0,0,143.910,6.390.804,28.048,353.102,0,8.724.975,679.949,0,118.891,34.536,283.290,0,150.351,92.881,0,0,2.906.118,2.602.877,0,127.485,175.756,0,0,0,0,10.383,5.128.525,2.944.514,854.578,0,1.270.179,59.254,0,0,0,0
4,2Q2017,2017,6,30,8.604.258,1.402.067,114.101,891.072,246.743,49.551,0,41.429,0,59.171,494.026,0,0,96.764,263.469,0,13.309,0,0,120.484,6.329.868,28.565,349.732,0,8.604.258,693.976,0,81.047,40.527,378.119,0,94.488,99.795,0,0,2.789.616,2.474.044,0,138.700,176.872,0,0,0,0,8.360,5.112.306,2.944.514,848.735,0,1.270.179,48.878,0,0,0,0

Renomeei a coluna "Month" para "Cluster_Month", pois como se trata de trimestre, ele agrupa ali três meses correspondentes áquele trimestre, então sabemos que colunas onde tem Cluster_Month 3, englona na verdade, os meses 1,2 e 3. E assim por diante com os demais.

A coluna dia não nos é mais útil aqui, então tiramos a coluna.

In [6]:
fundamental_data.rename(columns={'Month' : 'Cluster_Month'},inplace = True)
fundamental_data.drop('Day', axis=1, inplace=True)

fundamental_data.head()

,Quarter,Year,Cluster_Month,Ativo Total,Ativo Circulante,Caixa e Equivalentes de Caixa AC,Aplicações Financeiras AC,Contas a Receber AC,Estoques AC,Ativos Biológicos AC,Tributos a Recuperar AC,Despesas Antecipadas AC,Outros Ativos Circulantes AC,Ativo Realizavel Longo Prazo,Aplicações Financeiras Avaliadas a Valor Justo ACLP,Aplicações Financeiras Avaliadas ao Custo Amortizado ACLP,Contas a Receber ACLP,Estoques ACLP,Ativos Biológicos ACLP,Tributos Diferidos ACLP,Despesas Antecipadas ACLP,Créditos com Partes Relacionadas ACLP,Outros Ativos Não Circulantes ACLP,Investimentos,Imobilizado,Intangível,Diferido,Passivo Total,Passivo Circulante,Obrigações Sociais e Trabalhistas PC,Fornecedores PC,Obrigações Fiscais PC,Empréstimos e Financiamentos PC,Passivos com Partes Relacionadas PC,Dividendos e JCP a Pagar PC,Outros PC,Provisões PC,Passivos sobre Ativos Não-Correntes a Venda e Descontinuados PC,Passivo Não Circulante,Empréstimos e Financiamentos PNC,Passivos com Partes Relacionadas PNC,Outros PNC,Tributos Diferidos PNC,Adiantamento para Futuro Aumento Capital PNC,Provisões PNC,Passivos sobre Ativos Não-Correntes a Venda e Descontinuados PNC,Lucros e Receitas a Apropriar PNC,Participação dos Acionistas Não Controladores,Patrimônio Líquido,Capital Social Realizado,Reservas de Capital,Reservas de Reavaliação,Reservas de Lucros,Lucros/Prejuízos Acumulados,Ajustes de Avaliação Patrimonial,Ajustes Acumulados de Conversão,Outros Resultados Abrangentes,Adiantamento para Futuro Aumento Capital
0,2Q2018,2018,6,8.825.800,1.375.582,53.898,920.261,241.316,36.382,0,57.649,0,66.076,534.906,0,0,0,73.362,287.326,0,25.718,0,11.852,6.475.161,83.733,356.418,0,8.825.800,518.942,0,83.698,40.355,231.672,0,94.814,68.403,0,0,3.010.466,2.750.432,0,54.083,205.951,0,0,0,0,17.078,5.279.314,2.944.514,800.244,0,1.400.232,134.324,0,0,0,0
1,1Q2018,2018,3,8.536.529,1.109.223,60.812,705.529,225.510,38.002,0,16.422,0,62.948,532.018,0,0,78.309,277.833,0,25.445,0,0,150.431,6.454.152,86.117,355.019,0,8.536.529,514.126,0,99.432,34.181,266.519,0,40.348,73.646,0,0,2.731.562,2.460.283,0,84.026,187.253,0,0,0,0,16.913,5.273.928,2.944.514,831.033,0,1.400.232,98.149,0,0,0,0
2,4Q2017,2017,12,8.644.402,1.299.500,39.786,856.245,277.047,35.959,0,27.281,0,63.182,519.416,0,0,79.164,272.880,0,17.782,0,0,149.590,6.444.021,27.573,353.892,0,8.644.402,699.364,0,102.199,38.011,265.777,0,206.262,87.115,0,0,2.744.725,2.467.936,0,95.245,181.544,0,0,0,0,15.224,5.185.089,2.944.514,840.341,0,1.400.234,0,0,0,0,0
3,3Q2017,2017,9,8.724.975,1.442.779,145.357,925.503,245.011,37.474,0,33.336,0,56.098,510.242,0,0,86.213,266.674,0,13.445,0,0,143.910,6.390.804,28.048,353.102,0,8.724.975,679.949,0,118.891,34.536,283.290,0,150.351,92.881,0,0,2.906.118,2.602.877,0,127.485,175.756,0,0,0,0,10.383,5.128.525,2.944.514,854.578,0,1.270.179,59.254,0,0,0,0
4,2Q2017,2017,6,8.604.258,1.402.067,114.101,891.072,246.743,49.551,0,41.429,0,59.171,494.026,0,0,96.764,263.469,0,13.309,0,0,120.484,6.329.868,28.565,349.732,0,8.604.258,693.976,0,81.047,40.527,378.119,0,94.488,99.795,0,0,2.789.616,2.474.044,0,138.700,176.872,0,0,0,0,8.360,5.112.306,2.944.514,848.735,0,1.270.179,48.878,0,0,0,0

Correção de processamento, os dados vieram com "pontos" o que inviabiliza a manipulação númerica que o pandas compreende, assim tivemos que remover os pontos e atribuir o formato float, anteriormente veio com formato string.

Assim podemos ver a disposição dos números em relação a tabela gerada pela célula abaixo e a que tinhamos antes.

In [7]:
for key in ['Ativo Total','Ativo Circulante','Caixa e Equivalentes de Caixa AC','Aplicações Financeiras AC','Contas a Receber AC','Estoques AC', 'Ativos Biológicos AC','Tributos a Recuperar AC','Despesas Antecipadas AC','Outros Ativos Circulantes AC','Ativo Realizavel Longo Prazo ','Aplicações Financeiras Avaliadas a Valor Justo ACLP','Aplicações Financeiras Avaliadas ao Custo Amortizado ACLP','Contas a Receber ACLP','Estoques ACLP','Ativos Biológicos ACLP','Tributos Diferidos ACLP','Despesas Antecipadas ACLP','Créditos com Partes Relacionadas ACLP','Outros Ativos Não Circulantes ACLP','Investimentos','Imobilizado','Intangível','Diferido','Passivo Total','Passivo Circulante','Obrigações Sociais e Trabalhistas PC','Fornecedores PC','Obrigações Fiscais PC','Empréstimos e Financiamentos PC','Passivos com Partes Relacionadas PC','Dividendos e JCP a Pagar PC','Outros PC','Provisões PC', 'Passivos sobre Ativos Não-Correntes a Venda e Descontinuados PC', 'Passivo Não Circulante','Empréstimos e Financiamentos PNC','Passivos com Partes Relacionadas PNC','Outros PNC','Tributos Diferidos PNC','Adiantamento para Futuro Aumento Capital PNC','Provisões PNC','Passivos sobre Ativos Não-Correntes a Venda e Descontinuados PNC','Lucros e Receitas a Apropriar PNC','Participação dos Acionistas Não Controladores','Patrimônio Líquido','Capital Social Realizado','Reservas de Capital','Reservas de Reavaliação','Reservas de Lucros','Lucros/Prejuízos Acumulados','Ajustes de Avaliação Patrimonial','Ajustes Acumulados de Conversão','Outros Resultados Abrangentes','Adiantamento para Futuro Aumento Capital']:  
    fundamental_data[key] = fundamental_data[key].map(lambda x: str(x).replace(".", ""))
    fundamental_data[key] = fundamental_data[key].astype(float)
    
fundamental_data.head()

,Quarter,Year,Cluster_Month,Ativo Total,Ativo Circulante,Caixa e Equivalentes de Caixa AC,Aplicações Financeiras AC,Contas a Receber AC,Estoques AC,Ativos Biológicos AC,Tributos a Recuperar AC,Despesas Antecipadas AC,Outros Ativos Circulantes AC,Ativo Realizavel Longo Prazo,Aplicações Financeiras Avaliadas a Valor Justo ACLP,Aplicações Financeiras Avaliadas ao Custo Amortizado ACLP,Contas a Receber ACLP,Estoques ACLP,Ativos Biológicos ACLP,Tributos Diferidos ACLP,Despesas Antecipadas ACLP,Créditos com Partes Relacionadas ACLP,Outros Ativos Não Circulantes ACLP,Investimentos,Imobilizado,Intangível,Diferido,Passivo Total,Passivo Circulante,Obrigações Sociais e Trabalhistas PC,Fornecedores PC,Obrigações Fiscais PC,Empréstimos e Financiamentos PC,Passivos com Partes Relacionadas PC,Dividendos e JCP a Pagar PC,Outros PC,Provisões PC,Passivos sobre Ativos Não-Correntes a Venda e Descontinuados PC,Passivo Não Circulante,Empréstimos e Financiamentos PNC,Passivos com Partes Relacionadas PNC,Outros PNC,Tributos Diferidos PNC,Adiantamento para Futuro Aumento Capital PNC,Provisões PNC,Passivos sobre Ativos Não-Correntes a Venda e Descontinuados PNC,Lucros e Receitas a Apropriar PNC,Participação dos Acionistas Não Controladores,Patrimônio Líquido,Capital Social Realizado,Reservas de Capital,Reservas de Reavaliação,Reservas de Lucros,Lucros/Prejuízos Acumulados,Ajustes de Avaliação Patrimonial,Ajustes Acumulados de Conversão,Outros Resultados Abrangentes,Adiantamento para Futuro Aumento Capital
0,2Q2018,2018,6,8825800.0,1375582.0,53898.0,920261.0,241316.0,36382.0,0.0,57649.0,0.0,66076.0,534906.0,0.0,0.0,0.0,73362.0,287326.0,0.0,25718.0,0.0,11852.0,6475161.0,83733.0,356418.0,0.0,8825800.0,518942.0,0.0,83698.0,40355.0,231672.0,0.0,94814.0,68403.0,0.0,0.0,3010466.0,2750432.0,0.0,54083.0,205951.0,0.0,0.0,0.0,0.0,17078.0,5279314.0,2944514.0,800244.0,0.0,1400232.0,134324.0,0.0,0.0,0.0,0.0
1,1Q2018,2018,3,8536529.0,1109223.0,60812.0,705529.0,225510.0,38002.0,0.0,16422.0,0.0,62948.0,532018.0,0.0,0.0,78309.0,277833.0,0.0,25445.0,0.0,0.0,150431.0,6454152.0,86117.0,355019.0,0.0,8536529.0,514126.0,0.0,99432.0,34181.0,266519.0,0.0,40348.0,73646.0,0.0,0.0,2731562.0,2460283.0,0.0,84026.0,187253.0,0.0,0.0,0.0,0.0,16913.0,5273928.0,2944514.0,831033.0,0.0,1400232.0,98149.0,0.0,0.0,0.0,0.0
2,4Q2017,2017,12,8644402.0,1299500.0,39786.0,856245.0,277047.0,35959.0,0.0,27281.0,0.0,63182.0,519416.0,0.0,0.0,79164.0,272880.0,0.0,17782.0,0.0,0.0,149590.0,6444021.0,27573.0,353892.0,0.0,8644402.0,699364.0,0.0,102199.0,38011.0,265777.0,0.0,206262.0,87115.0,0.0,0.0,2744725.0,2467936.0,0.0,95245.0,181544.0,0.0,0.0,0.0,0.0,15224.0,5185089.0,2944514.0,840341.0,0.0,1400234.0,0.0,0.0,0.0,0.0,0.0
3,3Q2017,2017,9,8724975.0,1442779.0,145357.0,925503.0,245011.0,37474.0,0.0,33336.0,0.0,56098.0,510242.0,0.0,0.0,86213.0,266674.0,0.0,13445.0,0.0,0.0,143910.0,6390804.0,28048.0,353102.0,0.0,8724975.0,679949.0,0.0,118891.0,34536.0,283290.0,0.0,150351.0,92881.0,0.0,0.0,2906118.0,2602877.0,0.0,127485.0,175756.0,0.0,0.0,0.0,0.0,10383.0,5128525.0,2944514.0,854578.0,0.0,1270179.0,59254.0,0.0,0.0,0.0,0.0
4,2Q2017,2017,6,8604258.0,1402067.0,114101.0,891072.0,246743.0,49551.0,0.0,41429.0,0.0,59171.0,494026.0,0.0,0.0,96764.0,263469.0,0.0,13309.0,0.0,0.0,120484.0,6329868.0,28565.0,349732.0,0.0,8604258.0,693976.0,0.0,81047.0,40527.0,378119.0,0.0,94488.0,99795.0,0.0,0.0,2789616.0,2474044.0,0.0,138700.0,176872.0,0.0,0.0,0.0,0.0,8360.0,5112306.0,2944514.0,848735.0,0.0,1270179.0,48878.0,0.0,0.0,0.0,0.0

# DADOS DE PREÇO - API YAHOO FINANCE

Após determinandos os dados fundamentalistas da ação, chegou a hora de extrairmos os dados de preço da API aberta da Yahoo Finance.

Lembrando que temos que convertê-las ao formato de escala tempora de trimestre, para que possamos concatêna-las aos dados fundamentalistas, formando um dataset único da ação. Dados de preço e dados fundamentalistas referentes ao mesmo espaço temporal para cada amostra.

Abaixo, primeiro atribuimos a data de inicio e de fim que coletaremos os dados de preço, e depois trazemos o dataset com base nas datas, e 'm' nos diz respeito a escala temporal mês, como não há trimestre, tivemos que fazer a seguir a manipulação no código, com base nos dados originalmente mensais vindo da API.

In [8]:
start = datetime(2012, 6, 30)
end = datetime(2018, 5, 31)
price_data = web.get_data_yahoo('MULT3.SA', start, end, interval = 'm')

price_data.head()

                 High        Low       Open      Close      Volume  Adj Close
Date
2012-07-01  17.858999  16.159100  16.385700  17.272301  26912425.0  12.814696
2012-08-01  17.792299  16.715700  17.265699  17.268999  18383534.0  12.812247
2012-09-01  20.448799  17.118999  17.832300  19.895500  21844235.0  14.760907
2012-10-01  21.078800  19.018900  19.995501  19.832199  17483786.0  14.713941
2012-11-01  20.248800  18.932301  19.818899  19.665501  13256546.0  14.590265

As datas na coluna "Date" estavam como índíce, e usamos o code abaixo para tornar "Date" uma coluna normal do dataset, já que vamos precisar manipula-la.

In [9]:
price_data["Date"] = price_data.index
price_data.reset_index(drop=True, inplace=True)


date = price_data['Date']
price_data.drop(labels=['Date'], axis=1,inplace = True)
price_data.insert(0, 'Date', date)

price_data.head()

        Date       High        Low       Open      Close      Volume  Adj Close
0 2012-07-01  17.858999  16.159100  16.385700  17.272301  26912425.0  12.814696
1 2012-08-01  17.792299  16.715700  17.265699  17.268999  18383534.0  12.812247
2 2012-09-01  20.448799  17.118999  17.832300  19.895500  21844235.0  14.760907
3 2012-10-01  21.078800  19.018900  19.995501  19.832199  17483786.0  14.713941
4 2012-11-01  20.248800  18.932301  19.818899  19.665501  13256546.0  14.590265

Aqui começa a manipulação para transformarmos os dados de preço de escala mensal para escala trimestral.

Tal qual nos dados fundamentalistas, da coluna Date, criamos as colunas referentes a "dia", "mês" e "ano". Assim a coluna Date não nos é mais útil.

Manipulamos para colocar as três colunas referentes a data nas três primeiras posições das colunas no dataset.

In [10]:
price_data["Day"] = price_data['Date'].map(lambda x: x.day)
price_data["Month"] = price_data['Date'].map(lambda x: x.month)
price_data["Year"] = price_data['Date'].map(lambda x: x.year)

price_data.drop(columns = 'Date', inplace = True)



year = price_data['Year']
price_data.drop(labels=['Year'], axis=1,inplace = True)
price_data.insert(0, 'Year', year)

month = price_data['Month']
price_data.drop(labels=['Month'], axis=1,inplace = True)
price_data.insert(1, 'Month', month)

day = price_data['Day']
price_data.drop(labels=['Day'], axis=1,inplace = True)
price_data.insert(2, 'Day', day)

price_data.head()

   Year  Month  Day       High        Low       Open      Close      Volume  Adj Close
0  2012      7    1  17.858999  16.159100  16.385700  17.272301  26912425.0  12.814696
1  2012      8    1  17.792299  16.715700  17.265699  17.268999  18383534.0  12.812247
2  2012      9    1  20.448799  17.118999  17.832300  19.895500  21844235.0  14.760907
3  2012     10    1  21.078800  19.018900  19.995501  19.832199  17483786.0  14.713941
4  2012     11    1  20.248800  18.932301  19.818899  19.665501  13256546.0  14.590265

Nessa parte, o "for" percorre todas as linhas do dataset, e tal qual no padrão dos dados fundamentalistas, temos que atribuir aquele padrão que chamei de "Cluster_Month", onde o mês 3 representa o trimestre dos meses 1,2 e 3. Mês 6 o trimestre dos meses 4,5 e 6. E assim por diante.

Após, deletamos a coluna "dia", que não nos é útil.

In [11]:
for i,row in price_data.iterrows():   
    if (row['Month'] == 1) | (row['Month'] == 2) | (row['Month'] == 3):
        price_data.loc[i,'Month'] = 3
    
    elif (row['Month'] == 4) | (row['Month'] == 5) | (row['Month'] == 6):
         price_data.loc[i,'Month'] = 6
        
    elif (row['Month'] == 7) | (row['Month'] == 8) | (row['Month'] == 9):
         price_data.loc[i,'Month'] = 9
        
    else: 
          price_data.loc[i,'Month'] = 12



price_data.drop('Day', axis=1, inplace=True)

price_data.head()

   Year  Month       High        Low       Open      Close      Volume  Adj Close
0  2012      9  17.858999  16.159100  16.385700  17.272301  26912425.0  12.814696
1  2012      9  17.792299  16.715700  17.265699  17.268999  18383534.0  12.812247
2  2012      9  20.448799  17.118999  17.832300  19.895500  21844235.0  14.760907
3  2012     12  21.078800  19.018900  19.995501  19.832199  17483786.0  14.713941
4  2012     12  20.248800  18.932301  19.818899  19.665501  13256546.0  14.590265

E aqui tempos uma parte bem interessante. Agora agrupamos cada uma das três linhas correspondentes ao trimestre do ano correspondente.

Podemos olhar juntos para a primeira instrução abaixo e para a tabela acima para entender. Agrupamos por Ano e Mês, assim podemos ver as três primeiras linhas com "Month" igual a 3(na verdade são 1,2 e 3) que foram manipulados para facilitar esse processo. Então iremos agrupar essas três linhas, transformando em uma linha só correspondente ao primeiro trimestre de 2014 nesse caso. E assim convertemos os parâmetros de preço conforme suas especificidades.

- Abertura(Open): Utilização do método “first”, atribuindo o primeiro valor do trimestre.
   
- Fechamento(Close): Utilização do método “last”, atribuindo o último valor do trimestre.
      
- Máximo(High):Utilização do método “max”, atribuindo o máximo valor do trimestre.
 
- Mínimo(Low):Utilização do método “min”, atribuindo o mínimo valor do trimestre.

- Volume(Volume): Utilização do método “mean”, atribuindo a média dos valores do trimestre.

- Fechamento Ajustado(Adj Close):Utilização do método “mean”, atribuindo a média dos valores do trimestre.



Depois, novamente o processo de criar uma coluna "Quartes" com uma identificação mais intuitiva do trimestre e ano, e coloca-lo como a primeira posição das colunas.

Além de renomear a coluna "Month" para "Cluster_Month", tudo no mesmo padrão dos dados fundamentalistas.

In [12]:
final_data_price = price_data.groupby(['Year','Month']).agg({'High': 'max', 'Low': 'min', 'Open':'first', 'Close' : 'last', 'Volume':'mean', 'Adj Close':'mean'}).reset_index()


final_data_price['Quarter'] = '3Q2012','4Q2012', '1Q2013', '2Q2013', '3Q2013', '4Q2013','1Q2014', '2Q2014', '3Q2014','4Q2014', '1Q2015','2Q2015','3Q2015','4Q2015','1Q2016', '2Q2016', '3Q2016', '4Q2016','1Q2017','2Q2017','3Q2017','4Q2017','1Q2018','2Q2018'


quarter = final_data_price['Quarter']
final_data_price.drop(labels=['Quarter'], axis=1, inplace=True)
final_data_price.insert(0, 'Quarter', quarter)

final_data_price.head()

  Quarter  Year  Month       High        Low       Open    Close        Volume  Adj Close
0  3Q2012  2012      9  20.448799  16.159100  16.385700  19.8955  2.238006e+07  13.462617
1  4Q2012  2012     12  21.078800  18.932301  19.995501  20.0655  1.494764e+07  14.730412
2  1Q2013  2013      3  20.262199  17.992300  20.065500  19.4667  2.864318e+07  14.660314
3  2Q2013  2013      6  20.100000  16.066700  19.133301  17.2167  3.622110e+07  14.222832
4  3Q2013  2013      9  18.309999  15.583300  17.370001  17.6667  2.999870e+07  13.253023

# UNINDO DADOS DE PREÇO E DADOS FUNDAMENTALISTAS

Simplesmente fazendo um merge entre os dados de preço e fundamentalistas que tratamos até aqui.

A coluna "Year" e "Month" ficará repetida, então precisaremos renomear cada uma e excluir as outras duas que são a mesma coisa.

In [13]:
dataset = pd.merge(final_data_price, fundamental_data, how='left', on='Quarter')

dataset.rename(columns={'Year_x' : 'Year'},inplace = True)
dataset.rename(columns={'Cluster_Month_x' : 'Cluster_Month'},inplace = True)

dataset.drop('Year_y', axis=1, inplace=True)

dataset.drop('Cluster_Month', axis=1, inplace=True)

dataset.head()

,Quarter,Year,Month,High,Low,Open,Close,Volume,Adj Close,Ativo Total,Ativo Circulante,Caixa e Equivalentes de Caixa AC,Aplicações Financeiras AC,Contas a Receber AC,Estoques AC,Ativos Biológicos AC,Tributos a Recuperar AC,Despesas Antecipadas AC,Outros Ativos Circulantes AC,Ativo Realizavel Longo Prazo,Aplicações Financeiras Avaliadas a Valor Justo ACLP,Aplicações Financeiras Avaliadas ao Custo Amortizado ACLP,Contas a Receber ACLP,Estoques ACLP,Ativos Biológicos ACLP,Tributos Diferidos ACLP,Despesas Antecipadas ACLP,Créditos com Partes Relacionadas ACLP,Outros Ativos Não Circulantes ACLP,Investimentos,Imobilizado,Intangível,Diferido,Passivo Total,Passivo Circulante,Obrigações Sociais e Trabalhistas PC,Fornecedores PC,Obrigações Fiscais PC,Empréstimos e Financiamentos PC,Passivos com Partes Relacionadas PC,Dividendos e JCP a Pagar PC,Outros PC,Provisões PC,Passivos sobre Ativos Não-Correntes a Venda e Descontinuados PC,Passivo Não Circulante,Empréstimos e Financiamentos PNC,Passivos com Partes Relacionadas PNC,Outros PNC,Tributos Diferidos PNC,Adiantamento para Futuro Aumento Capital PNC,Provisões PNC,Passivos sobre Ativos Não-Correntes a Venda e Descontinuados PNC,Lucros e Receitas a Apropriar PNC,Participação dos Acionistas Não Controladores,Patrimônio Líquido,Capital Social Realizado,Reservas de Capital,Reservas de Reavaliação,Reservas de Lucros,Lucros/Prejuízos Acumulados,Ajustes de Avaliação Patrimonial,Ajustes Acumulados de Conversão,Outros Resultados Abrangentes,Adiantamento para Futuro Aumento Capital
0,3Q2012,2012,9,20.448799,16.159100,16.385700,19.8955,2.238006e+07,13.462617,5204608.0,708683.0,322707.0,1523.0,204170.0,135588.0,0.0,3593.0,0.0,41102.0,392927.0,0.0,0.0,35808.0,320862.0,0.0,0.0,0.0,0.0,36257.0,3753397.0,19265.0,330336.0,0.0,5204608.0,431130.0,0.0,214251.0,19726.0,81930.0,0.0,0.0,115223.0,0.0,0.0,1564439.0,1281181.0,0.0,190768.0,92490.0,0.0,0.0,0.0,0.0,110.0,3208929.0,1740646.0,933941.0,0.0,275540.0,258802.0,0.0,0.0,0.0,0.0
1,4Q2012,2012,12,21.078800,18.932301,19.995501,20.0655,1.494764e+07,14.730412,5684512.0,851338.0,392857.0,2144.0,219592.0,166084.0,0.0,28623.0,0.0,42038.0,440203.0,0.0,0.0,61473.0,333175.0,0.0,0.0,0.0,0.0,45555.0,4035068.0,17366.0,340537.0,0.0,5684512.0,549428.0,0.0,185325.0,19126.0,114353.0,0.0,106997.0,123627.0,0.0,0.0,1929744.0,1685281.0,0.0,142529.0,101934.0,0.0,0.0,0.0,0.0,131.0,3205209.0,1740646.0,837867.0,0.0,626696.0,0.0,0.0,0.0,0.0,0.0
2,1Q2013,2013,3,20.262199,17.992300,20.065500,19.4667,2.864318e+07,14.660314,5673374.0,674239.0,225376.0,2178.0,173113.0,195116.0,0.0,5318.0,23636.0,49502.0,436357.0,0.0,0.0,58206.0,335532.0,0.0,0.0,0.0,0.0,42619.0,4203820.0,17114.0,341844.0,0.0,5673374.0,544765.0,0.0,183156.0,22489.0,126725.0,0.0,106997.0,105398.0,0.0,0.0,1860484.0,1636121.0,0.0,118288.0,106075.0,0.0,0.0,0.0,0.0,138.0,3267987.0,1740646.0,830015.0,0.0,627451.0,69875.0,0.0,0.0,0.0,0.0
3,2Q2013,2013,6,20.100000,16.066700,19.133301,17.2167,3.622110e+07,14.222832,6120315.0,917947.0,172210.0,276421.0,180937.0,228702.0,0.0,14746.0,0.0,44931.0,436613.0,0.0,0.0,58071.0,337734.0,0.0,0.0,0.0,0.0,40808.0,4407308.0,17338.0,341109.0,0.0,6120315.0,482470.0,0.0,152395.0,33965.0,164629.0,0.0,38416.0,93065.0,0.0,0.0,1811672.0,1588567.0,0.0,108093.0,115012.0,0.0,0.0,0.0,0.0,157.0,3826016.0,2350906.0,810750.0,0.0,568961.0,95399.0,0.0,0.0,0.0,0.0
4,3Q2013,2013,9,18.309999,15.583300,17.370001,17.6667,2.999870e+07,13.253023,6393040.0,931896.0,309131.0,219632.0,198279.0,151166.0,0.0,1274.0,0.0,52414.0,445865.0,0.0,0.0,61570.0,339570.0,0.0,0.0,0.0,0.0,44725.0,4654685.0,17366.0,343228.0,0.0,6393040.0,472045.0,0.0,119238.0,33209.0,209620.0,0.0,38402.0,71576.0,0.0,0.0,2096320.0,1883709.0,0.0,89449.0,123162.0,0.0,0.0,0.0,0.0,171.0,3824504.0,2349451.0,769036.0,0.0,569194.0,136823.0,0.0,0.0,0.0,0.0

# CRIAÇÃO DO TARGET

## Good: Valorizou mais que 10% em um ano(4 trimestres)
## Bad: Não valorizou mais que 10% em um ano(4 trimestres)

Para criarmos o target, que será a variavel a ser predita nos nossos algoritmos de classificação, utilizamos o mesmo processo que na criação dos dados de preço forncecidos pela API da Yahoo Finance. Só que agora com algumas mudanças

Repare na data "end", ela tem exatamente um ano a mais que a que utilizamos na composição do dataset de preços, pois precisamos dessa janela que ficará "de fora" para compor o nosso target.

Imaginemos o seguinte: Analisando o trimestre atual, com todos os atributos de preço e fundamentalistas, o preço 4 trimestres depois(1 ano) aumentou 10% ?

Com base nessa lógica, precisamos desses dados de fora da janela para compor a coluna de target.

Ao final dessa célula, temos apenas o mesmo processamento dos dados de preço explicados antes, apenas com a diferença que temos 4 linhas de dados a mais, para que depois consigamos preencher o target.

In [14]:
##############################3COMEÇA O CÓDIGO QUE EXTRAI DADOS DE PREÇO - ALTERAR#################################
start = datetime(2012, 6, 30)
end = datetime(2019, 5, 31)
price_target = web.get_data_yahoo('MULT3.SA', start, end, interval = 'm')

price_target["Date"] = price_target.index
price_target.reset_index(drop=True, inplace=True)


date = price_target['Date']
price_target.drop(labels=['Date'], axis=1,inplace = True)
price_target.insert(0, 'Date', date)

price_target["Day"] = price_target['Date'].map(lambda x: x.day)
price_target["Month"] = price_target['Date'].map(lambda x: x.month)
price_target["Year"] = price_target['Date'].map(lambda x: x.year)

price_target.drop(columns = 'Date', inplace = True)



year = price_target['Year']
price_target.drop(labels=['Year'], axis=1,inplace = True)
price_target.insert(0, 'Year', year)

month = price_target['Month']
price_target.drop(labels=['Month'], axis=1,inplace = True)
price_target.insert(1, 'Month', month)

day = price_target['Day']
price_target.drop(labels=['Day'], axis=1,inplace = True)
price_target.insert(2, 'Day', day)



for i,row in price_target.iterrows():   
    if (row['Month'] == 1) | (row['Month'] == 2) | (row['Month'] == 3):
        price_target.loc[i,'Month'] = 3
    
    elif (row['Month'] == 4) | (row['Month'] == 5) | (row['Month'] == 6):
         price_target.loc[i,'Month'] = 6
        
    elif (row['Month'] == 7) | (row['Month'] == 8) | (row['Month'] == 9):
         price_target.loc[i,'Month'] = 9
        
    else: 
          price_target.loc[i,'Month'] = 12



price_target.drop('Day', axis=1, inplace=True)

final_price_target = price_target.groupby(['Year','Month']).agg({'High': 'max', 'Low': 'min', 'Open':'first', 'Close' : 'last', 'Volume':'mean', 'Adj Close':'mean'}).reset_index()

########################################ALTERAR##################################
final_price_target['Quarter'] =  '3Q2012','4Q2012', '1Q2013', '2Q2013', '3Q2013', '4Q2013','1Q2014', '2Q2014', '3Q2014','4Q2014', '1Q2015','2Q2015','3Q2015','4Q2015','1Q2016', '2Q2016', '3Q2016', '4Q2016','1Q2017','2Q2017','3Q2017','4Q2017','1Q2018','2Q2018','3Q2018','4Q2018','1Q2019','2Q2019'


quarter = final_price_target['Quarter']
final_price_target.drop(labels=['Quarter'], axis=1, inplace=True)
final_price_target.insert(0, 'Quarter', quarter)

final_price_target.rename(columns={'Month' : 'Cluster_Month'},inplace = True)

final_price_target.head()

  Quarter  Year  Cluster_Month       High        Low       Open    Close        Volume  Adj Close
0  3Q2012  2012              9  20.448799  16.159100  16.385700  19.8955  2.238006e+07  13.462617
1  4Q2012  2012             12  21.078800  18.932301  19.995501  20.0655  1.494764e+07  14.730412
2  1Q2013  2013              3  20.262199  17.992300  20.065500  19.4667  2.864318e+07  14.660314
3  2Q2013  2013              6  20.100000  16.066700  19.133301  17.2167  3.622110e+07  14.222832
4  3Q2013  2013              9  18.309999  15.583300  17.370001  17.6667  2.999870e+07  13.253023

Com base nesse dataset de preço, feito exclusivamente para preenchimento do target, constuiremos duas colunas, uma somente com os preços e a outra do target que usará essa coluna e a lógica explicada para preencher a classificação como "Good" ou "Bad".

In [15]:
price = final_price_target

price = price.iloc[0:,6].to_frame()

price["Date"] = price.index
price.reset_index(drop=True, inplace=True)

date = price['Date']
price.drop(labels=['Date'], axis=1,inplace = True)
price['target'] = ""

price = price.iloc[::-1]

price.head()

        Close target
27  24.840000
26  23.389999
25  24.309999
24  18.709999
23  19.000000

A logica abaixo percorre todas as linhas para preencher o target conforme as condições estabelecidas. Como os ultimos 4 são de fora da janela, ele são preenchidos com "Nan", serão cortados pois sua utilidade era ser base para preenchimento dos seus 4 anteriores.

In [16]:
for i,row in price.iterrows():
    if i > 23:
        price.loc[i,'target'] = 'NaN' 
    else:
        if price.loc[i+4,'Close'] >= (price.loc[i,'Close'] + (price.loc[i,'Close'] *0.1)):
            price.loc[i,'target'] = 'Good'
        else:
            price.loc[i,'target'] = 'Bad'

price.head()

        Close target
27  24.840000    NaN
26  23.389999    NaN
25  24.309999    NaN
24  18.709999    NaN
23  19.000000   Good

# UNIÃO DE TUDO: ÚLTIMA MANIPULAÇÃO

Finalmente, cortamos as linhas que não vamos usar(com 'nan' no target), e invertemos a ordem do dataset do target para coloca-lo em uma coluna "target" no dataset onde estão os dados de preço e fundamentalistas.

E por fim, usamos uma variavel auxiliar e inserimos a coluna target como a coluna na quarta posição do nosso dataset.

In [17]:
price = price.iloc[4:,:]
price = price.iloc[::-1]
price.reset_index(drop = True, inplace = True)
dataset['target'] = price.iloc[0:,1].to_frame()
data = dataset['target']
dataset.drop(labels=['target'], axis=1,inplace = True)
dataset.insert(3, 'target', data)

dataset.head()

,Quarter,Year,Month,target,High,Low,Open,Close,Volume,Adj Close,Ativo Total,Ativo Circulante,Caixa e Equivalentes de Caixa AC,Aplicações Financeiras AC,Contas a Receber AC,Estoques AC,Ativos Biológicos AC,Tributos a Recuperar AC,Despesas Antecipadas AC,Outros Ativos Circulantes AC,Ativo Realizavel Longo Prazo,Aplicações Financeiras Avaliadas a Valor Justo ACLP,Aplicações Financeiras Avaliadas ao Custo Amortizado ACLP,Contas a Receber ACLP,Estoques ACLP,Ativos Biológicos ACLP,Tributos Diferidos ACLP,Despesas Antecipadas ACLP,Créditos com Partes Relacionadas ACLP,Outros Ativos Não Circulantes ACLP,Investimentos,Imobilizado,Intangível,Diferido,Passivo Total,Passivo Circulante,Obrigações Sociais e Trabalhistas PC,Fornecedores PC,Obrigações Fiscais PC,Empréstimos e Financiamentos PC,Passivos com Partes Relacionadas PC,Dividendos e JCP a Pagar PC,Outros PC,Provisões PC,Passivos sobre Ativos Não-Correntes a Venda e Descontinuados PC,Passivo Não Circulante,Empréstimos e Financiamentos PNC,Passivos com Partes Relacionadas PNC,Outros PNC,Tributos Diferidos PNC,Adiantamento para Futuro Aumento Capital PNC,Provisões PNC,Passivos sobre Ativos Não-Correntes a Venda e Descontinuados PNC,Lucros e Receitas a Apropriar PNC,Participação dos Acionistas Não Controladores,Patrimônio Líquido,Capital Social Realizado,Reservas de Capital,Reservas de Reavaliação,Reservas de Lucros,Lucros/Prejuízos Acumulados,Ajustes de Avaliação Patrimonial,Ajustes Acumulados de Conversão,Outros Resultados Abrangentes,Adiantamento para Futuro Aumento Capital
0,3Q2012,2012,9,Bad,20.448799,16.159100,16.385700,19.8955,2.238006e+07,13.462617,5204608.0,708683.0,322707.0,1523.0,204170.0,135588.0,0.0,3593.0,0.0,41102.0,392927.0,0.0,0.0,35808.0,320862.0,0.0,0.0,0.0,0.0,36257.0,3753397.0,19265.0,330336.0,0.0,5204608.0,431130.0,0.0,214251.0,19726.0,81930.0,0.0,0.0,115223.0,0.0,0.0,1564439.0,1281181.0,0.0,190768.0,92490.0,0.0,0.0,0.0,0.0,110.0,3208929.0,1740646.0,933941.0,0.0,275540.0,258802.0,0.0,0.0,0.0,0.0
1,4Q2012,2012,12,Bad,21.078800,18.932301,19.995501,20.0655,1.494764e+07,14.730412,5684512.0,851338.0,392857.0,2144.0,219592.0,166084.0,0.0,28623.0,0.0,42038.0,440203.0,0.0,0.0,61473.0,333175.0,0.0,0.0,0.0,0.0,45555.0,4035068.0,17366.0,340537.0,0.0,5684512.0,549428.0,0.0,185325.0,19126.0,114353.0,0.0,106997.0,123627.0,0.0,0.0,1929744.0,1685281.0,0.0,142529.0,101934.0,0.0,0.0,0.0,0.0,131.0,3205209.0,1740646.0,837867.0,0.0,626696.0,0.0,0.0,0.0,0.0,0.0
2,1Q2013,2013,3,Bad,20.262199,17.992300,20.065500,19.4667,2.864318e+07,14.660314,5673374.0,674239.0,225376.0,2178.0,173113.0,195116.0,0.0,5318.0,23636.0,49502.0,436357.0,0.0,0.0,58206.0,335532.0,0.0,0.0,0.0,0.0,42619.0,4203820.0,17114.0,341844.0,0.0,5673374.0,544765.0,0.0,183156.0,22489.0,126725.0,0.0,106997.0,105398.0,0.0,0.0,1860484.0,1636121.0,0.0,118288.0,106075.0,0.0,0.0,0.0,0.0,138.0,3267987.0,1740646.0,830015.0,0.0,627451.0,69875.0,0.0,0.0,0.0,0.0
3,2Q2013,2013,6,Bad,20.100000,16.066700,19.133301,17.2167,3.622110e+07,14.222832,6120315.0,917947.0,172210.0,276421.0,180937.0,228702.0,0.0,14746.0,0.0,44931.0,436613.0,0.0,0.0,58071.0,337734.0,0.0,0.0,0.0,0.0,40808.0,4407308.0,17338.0,341109.0,0.0,6120315.0,482470.0,0.0,152395.0,33965.0,164629.0,0.0,38416.0,93065.0,0.0,0.0,1811672.0,1588567.0,0.0,108093.0,115012.0,0.0,0.0,0.0,0.0,157.0,3826016.0,2350906.0,810750.0,0.0,568961.0,95399.0,0.0,0.0,0.0,0.0
4,3Q2013,2013,9,Bad,18.309999,15.583300,17.370001,17.6667,2.999870e+07,13.253023,6393040.0,931896.0,309131.0,219632.0,198279.0,151166.0,0.0,1274.0,0.0,52414.0,445865.0,0.0,0.0,61570.0,339570.0,0.0,0.0,0.0,0.0,44725.0,4654685.0,17366.0,343228.0,0.0,6393040.0,472045.0,0.0,119238.0,33209.0,209620.0,0.0,38402.0,71576.0,0.0,0.0,2096320.0,1883709.0,0.0,89449.0,123162.0,0.0,0.0,0.0,0.0,171.0,3824504.0,2349451.0,769036.0,0.0,569194.0,136823.0,0.0,0.0,0.0,0.0

In [18]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 24 entries, 0 to 23
Data columns (total 65 columns):
Quarter                                                             24 non-null object
Year                                                                24 non-null int64
Month                                                               24 non-null int64
target                                                              24 non-null object
High                                                                24 non-null float64
Low                                                                 24 non-null float64
Open                                                                24 non-null float64
Close                                                               24 non-null float64
Volume                                                              24 non-null float64
Adj Close                                                           24 non-null float64
Ativo Total                                                         24 non-null float64
Ativo Circulante                                                    24 non-null float64
Caixa e Equivalentes de Caixa AC                                    24 non-null float64
Aplicações Financeiras AC                                           24 non-null float64
Contas a Receber AC                                                 24 non-null float64
Estoques AC                                                         24 non-null float64
Ativos Biológicos AC                                                24 non-null float64
Tributos a Recuperar AC                                             24 non-null float64
Despesas Antecipadas AC                                             24 non-null float64
Outros Ativos Circulantes AC                                        24 non-null float64
Ativo Realizavel Longo Prazo                                        24 non-null float64
Aplicações Financeiras Avaliadas a Valor Justo ACLP                 24 non-null float64
Aplicações Financeiras Avaliadas ao Custo Amortizado ACLP           24 non-null float64
Contas a Receber ACLP                                               24 non-null float64
Estoques ACLP                                                       24 non-null float64
Ativos Biológicos ACLP                                              24 non-null float64
Tributos Diferidos ACLP                                             24 non-null float64
Despesas Antecipadas ACLP                                           24 non-null float64
Créditos com Partes Relacionadas ACLP                               24 non-null float64
Outros Ativos Não Circulantes ACLP                                  24 non-null float64
Investimentos                                                       24 non-null float64
Imobilizado                                                         24 non-null float64
Intangível                                                          24 non-null float64
Diferido                                                            24 non-null float64
Passivo Total                                                       24 non-null float64
Passivo Circulante                                                  24 non-null float64
Obrigações Sociais e Trabalhistas PC                                24 non-null float64
Fornecedores PC                                                     24 non-null float64
Obrigações Fiscais PC                                               24 non-null float64
Empréstimos e Financiamentos PC                                     24 non-null float64
Passivos com Partes Relacionadas PC                                 24 non-null float64
Dividendos e JCP a Pagar PC                                         24 non-null float64
Outros PC                                                           24 non-null float64
Provisões PC                                                        24 non-null float64
Passivos sobre Ativos Não-Correntes a Venda e Descontinuados PC     24 non-null float64
Passivo Não Circulante                                              24 non-null float64
Empréstimos e Financiamentos PNC                                    24 non-null float64
Passivos com Partes Relacionadas PNC                                24 non-null float64
Outros PNC                                                          24 non-null float64
Tributos Diferidos PNC                                              24 non-null float64
Adiantamento para Futuro Aumento Capital PNC                        24 non-null float64
Provisões PNC                                                       24 non-null float64
Passivos sobre Ativos Não-Correntes a Venda e Descontinuados PNC    24 non-null float64
Lucros e Receitas a Apropriar PNC                                   24 non-null float64
Participação dos Acionistas Não Controladores                       24 non-null float64
Patrimônio Líquido                                                  24 non-null float64
Capital Social Realizado                                            24 non-null float64
Reservas de Capital                                                 24 non-null float64
Reservas de Reavaliação                                             24 non-null float64
Reservas de Lucros                                                  24 non-null float64
Lucros/Prejuízos Acumulados                                         24 non-null float64
Ajustes de Avaliação Patrimonial                                    24 non-null float64
Ajustes Acumulados de Conversão                                     24 non-null float64
Outros Resultados Abrangentes                                       24 non-null float64
Adiantamento para Futuro Aumento Capital                            24 non-null float64
dtypes: float64(61), int64(2), object(2)
memory usage: 12.4+ KB

In [19]:
dataset.to_csv("FINAL_CODE_MULT3.csv", index= False)